# Generated by Django 6.0.5 on 2026-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0002_scene_outputs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
