steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ss-tool-498115/fpa-web:$COMMIT_SHA', '.']
    dir: 'fpa_web'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ss-tool-498115/fpa-web:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - fpa-web
      - --image=gcr.io/ss-tool-498115/fpa-web:$COMMIT_SHA
      - --region=europe-west1
      - --project=ss-tool-498115
      - --vpc-connector=fpa-redis-connector
      - --vpc-egress=private-ranges-only
      - --service-account=fpa-app@ss-tool-498115.iam.gserviceaccount.com
      - --memory=2Gi
      - --cpu=2
      - --timeout=600
      - --allow-unauthenticated
      - --set-env-vars=DJANGO_SETTINGS_MODULE=config.settings.gcp,POSTGRES_DB=fpa_db,POSTGRES_USER=adminuser,POSTGRES_PASSWORD=FpaAdmin2026,POSTGRES_HOST=34.38.74.145,POSTGRES_PORT=5432,REDIS_URL=redis://10.112.227.243:6379/0,USE_GCS=true,GCS_BUCKET_NAME=ss-tool-fpa-media,GCP_PROJECT_ID=ss-tool-498115,CLOUD_SQL_CONNECTION_NAME=ss-tool-498115:europe-west1:fpa-postgres,SECURE_SSL_REDIRECT=false,SECRET_KEY=change-me-to-something-secure

images:
  - 'gcr.io/ss-tool-498115/fpa-web:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
